version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gopti
      POSTGRES_PASSWORD: gopti
      POSTGRES_DB: gopti
    ports: ["5433:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata: